/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2020-03-14 04:41:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class default_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>인사 인덱스</title>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\"#signUP\").click(function(){\t\r\n");
      out.write("\t \t\t\t$(\"#selectHuman\")\r\n");
      out.write("\t \t\t\t.attr(\"enctype\",\"multipart/form-data\")\r\n");
      out.write("\t \t\t\t.attr(\"action\",\"/etc/moveSignup.td\")\r\n");
      out.write("\t            .submit();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#select\").click(function(){\t\t\t\t\r\n");
      out.write("\t \t\t\t$(\"#selectHuman\")\r\n");
      out.write("\t \t\t\t.attr(\"action\",\"/human/select.td\")\r\n");
      out.write("\t            .submit();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#reference\").click(function(){\t\t\t\t\r\n");
      out.write("\t \t\t\t$(\"#selectHuman\")\r\n");
      out.write("\t \t\t\t.attr(\"action\",\"/human/reference.td\")\r\n");
      out.write("\t            .submit();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#selectappt\").click(function(){\t\t\t\t\r\n");
      out.write("\t \t\t\t$(\"#selectHuman\")\r\n");
      out.write("\t \t\t\t.attr(\"action\",\"/human/apptRecord.td\")\r\n");
      out.write("\t            .submit();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#commuteRecord\").click(function(){\t\t\t\t\r\n");
      out.write("\t \t\t\t$(\"#selectHuman\")\r\n");
      out.write("\t \t\t\t.attr(\"action\",\"/human/commuteRecord.td\")\r\n");
      out.write("\t            .submit();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#deptReference\").click(function(){\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"/human/deptAuthority.td\",\r\n");
      out.write("\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\t\terror:function(){\r\n");
      out.write("\t\t\t\t\t\talert('시스템 오류 입니다. 관리자에게 문의 하세요');\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess:function(resultData){\r\n");
      out.write("\t\t\t\t\t\tif(resultData==false){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#msg\").text(\"권한이 불충분합니다.\").css(\"color\",\"#000099\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(resultData==true){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#selectHuman\")\r\n");
      out.write("\t\t\t\t \t\t\t.attr(\"action\",\"/human/deptReference.td\")\r\n");
      out.write("\t\t\t\t            .submit();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#approval\").click(function(){\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"/human/Authority.td\",\r\n");
      out.write("\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\t\terror:function(){\r\n");
      out.write("\t\t\t\t\t\talert('시스템 오류 입니다. 관리자에게 문의 하세요');\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess:function(resultData){\r\n");
      out.write("\t\t\t\t\t\tif(resultData==false){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#msg\").text(\"권한이 불충분합니다.\").css(\"color\",\"#000099\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(resultData==true){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#selectHuman\")\r\n");
      out.write("\t\t\t\t \t\t\t.attr(\"action\",\"/human/selectAppr.td\")\r\n");
      out.write("\t\t\t\t            .submit();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#appointment\").click(function(){\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"/human/Authority.td\",\r\n");
      out.write("\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\t\terror:function(){\r\n");
      out.write("\t\t\t\t\t\talert('시스템 오류 입니다. 관리자에게 문의 하세요');\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess:function(resultData){\r\n");
      out.write("\t\t\t\t\t\tif(resultData==false){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#msg\").text(\"권한이 불충분합니다.\").css(\"color\",\"#000099\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(resultData==true){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#selectHuman\")\r\n");
      out.write("\t\t\t\t \t\t\t.attr(\"action\",\"/human/apptSelect.td\")\r\n");
      out.write("\t\t\t\t            .submit();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#deptCommRecord\").click(function(){\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"/human/deptAuthority.td\",\r\n");
      out.write("\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\t\terror:function(){\r\n");
      out.write("\t\t\t\t\t\talert('시스템 오류 입니다. 관리자에게 문의 하세요');\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess:function(resultData){\r\n");
      out.write("\t\t\t\t\t\tif(resultData==false){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#msg\").text(\"권한이 불충분합니다.\").css(\"color\",\"#000099\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(resultData==true){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#selectHuman\")\r\n");
      out.write("\t\t\t\t \t\t\t.attr(\"action\",\"/human/selectAllcommRecord.td\")\r\n");
      out.write("\t\t\t\t            .submit();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\t\t\r\n");
      out.write("\t\t <form id=\"selectHuman\" name=\"selectHuman\" method=\"POST\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"signUP\" id=\"signUP\" value=\"회원가입\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"select\" id=\"select\" value=\"사원현황\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"reference\" id=\"reference\" value=\"인사정보 조회\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"deptReference\" id=\"deptReference\" value=\"부서 인사정보 조회\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"approval\" id=\"approval\" value=\"회원등록 승인 페이지\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"appointment\" id=\"appointment\" value=\"인사발령\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"selectappt\" id=\"selectappt\" value=\"인사발령 조회\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"commuteRecord\" id=\"commuteRecord\" value=\"출퇴근 기록 조회\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"deptCommRecord\" id=\"deptCommRecord\" value=\"부서 출퇴근 기록 조회\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<span id=\"msg\"></span>    \r\n");
      out.write("\t\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
