/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2020-03-16 01:48:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.human;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java142.todak.human.vo.MemberVO;

public final class apptMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java142.todak.human.vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");

		Object obj=request.getAttribute("mvo");
		MemberVO mvo=(MemberVO)obj;
		String bposition=mvo.getHm_position();
		String bduty=mvo.getHm_duty();
		String bdept=mvo.getHm_deptnum();
		String bteam=mvo.getHm_teamnum();
		switch(bposition){
		case "임원":
			bposition="13";
			break;
		case "부장":
			bposition="14";
			break;
		case "과장":
			bposition="15";
			break;
		case "대리":
			bposition="16";
			break;
		case "사원":
			bposition="17";
			break;
	}
		switch(bduty){
		case "팀장":
			bduty="18";
			break;
		case "본부장":
			bduty="19";
			break;
		case "대표이사":
			bduty="20";
			break;
		case "없음":
			bduty="73";
			break;
	}
		switch(bdept){
		case "경영지원본부":
			bdept="00";
			break;
		case "전략기획본부":
			bdept="01";
			break;
		case "마케팅본부":
			bdept="02";
			break;
		case "나눔사업본부":
			bdept="03";
			break;
	}
		switch(bteam){
		case "인재경영팀":
			bteam="04";
			break;
		case "재무팀":
			bteam="05";
			break;
		case "관리팀":
			bteam="06";
			break;
		case "기획팀":
			bteam="07";
			break;
		case "소통협력팀":
			bteam="08";
			break;
		case "IT팀":
			bteam="09";
			break;
		case "홍보팀":
			bteam="10";
			break;
		case "배분팀":
			bteam="11";
			break;
		case "혁신사업팀":
			bteam="12";
			break;
		case "없음":
			bteam="73";
			break;
	}
		

      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"https://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"./jquery-ui-1.12.1/datepicker-ko.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\".promotion\").hide();\r\n");
      out.write("\t\t$(\".deptTransfer\").hide();\r\n");
      out.write("\t\t$(\".notes\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#accept\").click(function(){\t\r\n");
      out.write(" \t\t\t$(\"#apptMember\")\r\n");
      out.write(" \t\t\t.attr(\"action\",\"/human/updateAppt.td\")\r\n");
      out.write("            .submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#hpa_appointment\").change(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif($(\"#hpa_appointment\").val()==\"68\"){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\".promotion\").show();\r\n");
      out.write("\t\t\t\t$(\".notes\").show();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\".promotion\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif($(\"#hpa_appointment\").val()==\"69\"){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\".deptTransfer\").show();\r\n");
      out.write("\t\t\t\t$(\".notes\").show();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\".deptTransfer\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif($(\"#hpa_appointment\").val()==\"67\"){\r\n");
      out.write("\t\t\t\t$(\".promotion\").hide();\r\n");
      out.write("\t\t\t\t$(\".deptTransfer\").hide();\r\n");
      out.write("\t\t\t\t$(\".notes\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif($(\"#hpa_appointment\").val()==\"74\"){\r\n");
      out.write("\t\t\t\t$(\".promotion\").hide();\r\n");
      out.write("\t\t\t\t$(\".deptTransfer\").hide();\r\n");
      out.write("\t\t\t\t$(\".notes\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t    $(\"#hpa_appointmentdate\").datepicker({\r\n");
      out.write("\t    \t dateFormat: 'yymmdd'\r\n");
      out.write("\t    \t,showMonthAfterYear:true             \r\n");
      out.write("\t        ,yearSuffix: \"년\" \r\n");
      out.write("\t       \t,changeYear: true //콤보박스에서 년 선택 가능\r\n");
      out.write("\t        ,changeMonth: true //콤보박스에서 월 선택 가능       \r\n");
      out.write("\t        ,monthNamesShort: ['1','2','3','4','5','6','7','8','9','10','11','12'] \r\n");
      out.write("\t        ,monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'] \r\n");
      out.write("\t        ,dayNamesMin: ['일','월','화','수','목','금','토']\r\n");
      out.write("\t        ,dayNames: ['일요일','월요일','화요일','수요일','목요일','금요일','토요일']\r\n");
      out.write("\t    });\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<form   name=\"apptMember\"\r\n");
      out.write("\t\t  \t\t\tid=\"apptMember\"\r\n");
      out.write("\t\t \t\t    method=\"POST\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr><th><h4>인사발령</h4></th></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"height: 200px; width: 735px; border:1px solid black;\">\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">발령구분\r\n");
      out.write("\t\t\t\t\t\t\t<SELECT name = \"hpa_appointment\" id=\"hpa_appointment\">\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION VALUE=\"67\">== 선택  ==</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION VALUE=\"68\">승진</OPTION>\r\n");
      out.write("\t\t\t\t\t\t    <OPTION VALUE=\"69\">부서이동</OPTION>\r\n");
      out.write("\t\t\t\t\t\t    <OPTION VALUE=\"74\">퇴사</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t 발령일자<input type=\"text\" name=\"hpa_appointmentdate\" id=\"hpa_appointmentdate\" size=\"12\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"promotion\">\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t현재직위 : ");
      out.print(mvo.getHm_position() );
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t발령직위 :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<SELECT name = \"hpa_aposition\" id=\"hpa_aposition\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"67\">== 선택  ==</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"13\">임원</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"14\">부장</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"15\">과장</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"16\">대리</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"17\">사원</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t현재직책 : ");
      out.print(mvo.getHm_duty() );
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t발령직책 :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<SELECT name = \"hpa_aduty\" id=\"hpa_aduty\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"67\">==선택==</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"18\">팀장</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"19\">본부장</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"20\">대표이사</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"73\">없음</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"deptTransfer\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t현재부서 : ");
      out.print(mvo.getHm_deptnum() );
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t발령부서 :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<SELECT name = \"hpa_adept\" id=\"hpa_adept\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"67\">== 선택  ==</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"00\">경영지원본부</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"01\">전략기획본부</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"02\">마케팅본부</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"03\">나눔사업본부</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t현재팀 : ");
      out.print(mvo.getHm_teamnum() );
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t발령팀 :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<SELECT name = \"hpa_ateam\" id=\"hpa_ateam\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"67\">== 선택  ==</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"04\">인재경영팀</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"05\">재무팀</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"06\">관리팀</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"07\">기획팀</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"08\">소통협력팀</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"09\">IT팀</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"10\">홍보팀</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"11\">배분팀</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"12\">혁신사업팀</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"73\">없음</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"notes\">\r\n");
      out.write("\t\t\t\t\t\t\t <tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t비고:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea rows=\"5\" cols=\"50\" name=\"hpa_contents\" id=\"hpa_contents\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \t\t    <input type=\"hidden\" name=\"hpa_empnum\" id=\"hpa_empnum\" value=\"");
      out.print(mvo.getHm_empnum() );
      out.write("\"/>\r\n");
      out.write("\t\t \t\t    <input type=\"hidden\" name=\"hpa_name\" id=\"hpa_name\" value=\"");
      out.print(mvo.getHm_name() );
      out.write("\"/>\r\n");
      out.write("\t\t \t\t    <input type=\"hidden\" name=\"hpa_bposition\" id=\"hpa_bposition\" value=\"");
      out.print(bposition);
      out.write("\"/>\r\n");
      out.write("\t\t \t\t    <input type=\"hidden\" name=\"hpa_bduty\" id=\"hpa_bduty\" value=\"");
      out.print(bduty);
      out.write("\"/>\r\n");
      out.write("\t\t \t\t    <input type=\"hidden\" name=\"hpa_bdept\" id=\"hpa_bdept\" value=\"");
      out.print(bdept);
      out.write("\"/>\r\n");
      out.write("\t\t \t\t    <input type=\"hidden\" name=\"hpa_bteam\" id=\"hpa_bteam\" value=\"");
      out.print(bteam );
      out.write("\"/>\r\n");
      out.write("\t\t   </form>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"120px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"120px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"120px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"120px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"120px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"120px\"/>\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>사원번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>성명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>직급</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>직책</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>부서</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>팀</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(mvo.getHm_empnum() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(mvo.getHm_name() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(mvo.getHm_position() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(mvo.getHm_duty() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(mvo.getHm_deptnum() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(mvo.getHm_teamnum() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"발령등록\" name=\"accept\" id=\"accept\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
