/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2020-03-16 01:48:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.human;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java142.todak.human.vo.MemberVO;
import java142.todak.common.vo.PagingVO;

public final class selectApptMem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java142.todak.common.vo.PagingVO");
    _jspx_imports_classes.add("java142.todak.human.vo.MemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write(" \r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
	
		Object obj=request.getAttribute("apptList");
		ArrayList aList =(ArrayList) obj;
		
		Object obj2=request.getAttribute("mvo");
		MemberVO pvo=(MemberVO) obj2;
		String key=pvo.getKeyword();
		String ser=pvo.getSearch();
		
		String dept=null;
		String team=null;
		int Size=pvo.getPageSize();
		System.out.println(">>>>>>>>>>>>>>>"+key);
		System.out.println("<<<<<<<<<<<<<<<"+ser);
		
		
		int pageSize = pvo.getPageSize();
		int groupSize = pvo.getGroupSize();
		int curPage = pvo.getCurPage();
		int totalCount = pvo.getTotalCount();
		
		if(request.getParameter("curPage") != null)
		{
			curPage = Integer.parseInt(request.getParameter("curPage"));
		}
		
	
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>인사발령</title>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"https://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tif('");
      out.print(key );
      out.write("' != 'null'){\r\n");
      out.write("\t\t\t\t$(\"#keyword\").val('");
      out.print(key );
      out.write("');\r\n");
      out.write("\t\t\t\t$(\"#search\").val('");
      out.print(ser );
      out.write("');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif('");
      out.print(Size );
      out.write("' > 0){\r\n");
      out.write("\t\t\t\t$(\"#pageCtrl\").val('");
      out.print(Size );
      out.write("');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#search\").change(function(){\r\n");
      out.write("\t\t\t\tif($(\"#search\").val()==\"all\"){\r\n");
      out.write("\t\t\t\t\t$(\"#keyword\").val(\"전체목록을 조회\");\r\n");
      out.write("\t\t\t\t}else if($(\"#search\").val()!=\"all\"){\r\n");
      out.write("\t\t\t\t\t$(\"#keyword\").val(\"\");\r\n");
      out.write("\t\t\t\t\t$(\"#keyword\").focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#selectData\").click(function(){\r\n");
      out.write("\t\t\t\tif($(\"#search\").val()!=\"all\"){\r\n");
      out.write("\t\t\t\t\tif(!chkSubmit($('#keyword'),\"검색어를\"))return;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tgoPage(1);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#pageCtrl\").change(function(){\r\n");
      out.write("\t\t\t\tgoPage(1);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\".goDetail\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar empnum=$(this).parents(\"tr\").attr(\"data\");\r\n");
      out.write("\t\t\t\t$(\"#hm_empnum\").val(empnum);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#detailForm\").attr({\r\n");
      out.write("\t\t\t\t\t\"method\":\"get\",\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\"action\":\"/human/appointment.td\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#detailForm\").submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction goPage(page){\r\n");
      out.write("\t\t\tif($(\"#search\").val()==\"all\"){\r\n");
      out.write("\t\t\t\t$(\"#keyword\").val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#page\").val(page);\r\n");
      out.write("\t\t\t$(\"#PageSearch\").attr({\r\n");
      out.write("\t\t\t\t\"method\":\"get\",\r\n");
      out.write("\t\t\t\t\"action\":\"/human/apptSelect.td\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#PageSearch\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction chkSubmit(v_item,v_msg){\r\n");
      out.write("\t\t\tif(v_item.val().replace(/\\s/g,\"\")==\"\"){\r\n");
      out.write("\t\t\t\talert(v_msg+\"확인해 주세요.\");\r\n");
      out.write("\t\t\t\tv_item.val(\"\");\r\n");
      out.write("\t\t\t\tv_item.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\t<div id=\"memberList\">\r\n");
      out.write("\t\t<table summary=\"사원 조회\">\r\n");
      out.write("\t\t\t<table border=\"1\" align=\"center\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<thead>\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>사원번호</th>\r\n");
      out.write("\t\t\t\t\t<th>성명</th>\r\n");
      out.write("\t\t\t\t\t<th>부서</th>\r\n");
      out.write("\t\t\t\t\t<th>팀</th>\r\n");
      out.write("\t\t\t\t\t<th>직위</th>\r\n");
      out.write("\t\t\t\t\t<th>생년월일</th>\r\n");
      out.write("\t\t\t\t\t<th>입사일</th>\r\n");
      out.write("\t\t\t\t\t<th>핸드폰</th>\r\n");
      out.write("\t\t\t\t\t<th>내선번호</th>\r\n");
      out.write("\t\t\t\t\t<th>구분</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");


			
	
			if(aList.size()!=0)
			{
				MemberVO mvo=(MemberVO)aList.get(0);
		
				for(int i=0;i<aList.size();i++){
					mvo=(MemberVO)aList.get(i);

      out.write("\r\n");
      out.write("\t\t\t\t<tr data='");
      out.print(mvo.getHm_empnum() );
      out.write("'>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(mvo.getHm_empnum() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"goDetail\">");
      out.print(mvo.getHm_name() );
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(mvo.getHm_deptnum() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(mvo.getHm_teamnum() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(mvo.getHm_position() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(mvo.getHm_birth() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(mvo.getHm_hiredate() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(mvo.getHm_hp() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(mvo.getHm_extensionnum() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(mvo.getHm_employmenttype() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");

			
				}
			}
			if(aList.size()==0){

      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr><td colspan=\"5\">조회된 정보가 없습니다.</td>\r\n");

			}

      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</table>\t\r\n");
      out.write(" \t<div id=\"StatusSearch\" name=\"StatusSearch\">\r\n");
      out.write("\t\t\t<form id=\"PageSearch\" name=\"PageSearch\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"page\" name=\"page\" value=\"1\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<table summary=\"검색\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"std1\">\r\n");
      out.write("\t\t\t\t\t\t<label>검색조건</label>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"search\" name=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"all\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hm_name\">성명</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hm_deptnum\">부서명</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hm_position\">직위</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hm_employmenttype\">고용 형태</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"keyword\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"keyword\" value=\"검색어를 입력하세요\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"검색\" id=\"selectData\"/>\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"std1\">\r\n");
      out.write("\t\t\t\t\t\t<select id=\"pageCtrl\" name=\"pageCtrl\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5줄</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10줄</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20\">20줄</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"30\">30줄</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write(" \t\t<form name=\"detailForm\" id=\"detailForm\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"hm_empnum\" id=\"hm_empnum\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "paging.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("url", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("/human/apptSelect.td", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("str", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageSize", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(pageSize), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("groupSize", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(groupSize), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("curPage", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(curPage), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("totalCount", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(totalCount), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("key", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(key), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("ser", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(ser), request.getCharacterEncoding()), out, true);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
